### ISSUE TITLE
"Unable to translate xn----5da7e.de to Unicode"

### ISSUE THREAD

**Issue by timbowhite** [centralnicgroup-opensource/rtldev-middleware-idna-uts46#638]
Thanks for this module.

I'm not sure if this is expected behavior, but the following code throws "Error: Unable to translate xn----5da7e.de to Unicode."
```
import { convert, toAscii, toUnicode } from 'idna-uts46-hx';

let str = 'xn----5da7e.de'; // Ä-Ü.de
console.log(toUnicode(str));
```

Expected output would be:
```
ä-ü.de
```

**Comment by KaiSchwarz-cnic** [comment]
thanks for reporting, we'll have an eye on this.

**Comment by AsifNawaz-cnic** [comment]
Hi @timbowhite ,

Thanks for pointing this out!

The issue with `xn----5da7e.de` (which translates to `Ä-Ü.de`) returning an "invalid" error is actually expected. Our idna46 converter follows the IDNA2008 standard, which only allows domain names to be in lowercase. Uppercase letters are no longer valid under this standard, unlike the older IDNA2003 standard that did allow them. So, when our converter sees uppercase input like `Ä-Ü.de`, it flags it as invalid to stay compliant with IDNA2008.

To fix this, you just need to make sure the domain name is in lowercase. Here’s what the correct formats should look like:
- **Lowercase IDN:** `ä-ü.de`
- **Lowercase Punycode:** `xn----zfa7e.de`

We also checked the WHOIS information for both versions. The WHOIS query for `xn----5da7e.de` (which corresponds to `Ä-Ü.de`) returns an "invalid" status, which is consistent with IDNA2008 rules. However, the correctly formatted punycode `xn----zfa7e.de` (for `ä-ü.de`) shows a "Status: connect," confirming it as valid.

![image](https://github.com/user-attachments/assets/3d2d0388-f4eb-4ea1-9f18-0bfe15aeeec3)

Our tool is designed to handle and translate valid domain names. When it encounters an invalid domain name like `xn----5da7e.de`, it throws an error because it can't translate an invalid format. While throwing an error isn’t perfect, it at least signals that the domain name doesn’t comply with the current standards and needs adjustment.

Here’s the relevant part of the function that handles this:

```javascript
function toUnicode(domainName, options = {}) {
  const idn = tr46.toUnicode(domainName, {
    ...getDefaultOptions(domainName),
    ...options,
  });
  if (idn !== null && !idn.error) {
    return idn.domain;
  }
  throw new Error(`Unable to translate ${domainName} to Unicode.`);
}
```

As you can see, if the domain is valid, it gets translated to Unicode. If not, it throws an error, which helps users identify when something is off with the domain format.

For more details on these requirements, you can check out the [Unicode FAQ on IDNs](https://www.unicode.org/faq/idn.html), which explains the differences between IDNA2003 and IDNA2008.

Let us know if you have any other questions or need further assistance!
